name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [master]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: lumirelle/workflows/setup-bun@v3

      - name: Update sponsors
        run: nr build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: lumirelle
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}
          SPONSORKIT_OPENCOLLECTIVE_SLUG: lumirelle
          SPONSORKIT_OPENCOLLECTIVE_TYPE: person
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update sponsors.svg [ci skip]"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
